export type InAppActionType = 'search' | 'play' | 'navigate' | 'message' | 'view' | 'calculate' | 'compose' | 'camera_mode' | 'setting' | 'launch';

export interface InAppActionConfig {
  searchUrlTemplate?: string; // e.g. 'https://www.youtube.com/results?search_query={q}'
  searchIntentTemplate?: string; // e.g. 'intent://www.youtube.com/results?search_query={q}#Intent;package=com.google.android.youtube;scheme=https;end'
  defaultQueryPlaceholder?: string;
  quickSuggestions?: string[];
  supportedActions?: InAppActionType[];
}

export interface AppItem {
  id: string;
  name: string;
  category: 'Social' | 'Productivity' | 'Media' | 'Utilities' | 'System' | 'Tools' | 'Games';
  packageName: string;
  scheme: string;
  fallbackUrl: string;
  iconBg: string;
  iconColor: string;
  iconType: 'youtube' | 'whatsapp' | 'chrome' | 'settings' | 'camera' | 'calculator' | 'instagram' | 'spotify' | 'gmail' | 'maps' | 'twitter' | 'netflix' | 'telegram' | 'contacts' | 'calendar' | 'photos' | 'drive' | 'clock' | 'phone' | 'messages' | 'store' | 'file' | 'reddit' | 'amazon' | 'github' | 'music' | 'generic';
  keywords: string[];
  description: string;
  isSystem?: boolean;
  actionConfig?: InAppActionConfig;
}

export const INSTALLED_APPS: AppItem[] = [
  {
    id: 'source_ai',
    name: 'Source AI',
    category: 'Productivity',
    packageName: 'ai.source.workspace',
    scheme: '#',
    fallbackUrl: '#',
    iconBg: 'from-cyan-500 via-blue-600 to-indigo-600',
    iconColor: '#FFFFFF',
    iconType: 'generic',
    keywords: ['source ai', 'source', 'sourceai', 'open source ai', 'ai assistant', 'rishi', 'gemini', 'instructions', 'open the app', 'the app', 'this app'],
    description: 'Source AI - Intelligent autonomous assistant workspace and device agent.',
    isSystem: true,
    actionConfig: {
      defaultQueryPlaceholder: 'Give instructions to Source AI...',
      quickSuggestions: ['Follow instructions', 'Explain this topic', 'Perform deep research', 'Write code'],
      supportedActions: ['launch', 'view', 'compose'],
    },
  },
  {
    id: 'gemini_support',
    name: 'Gemini Support & Booking',
    category: 'Productivity',
    packageName: 'ai.gemini.support',
    scheme: '#',
    fallbackUrl: '#',
    iconBg: 'from-purple-600 to-indigo-700',
    iconColor: '#FFFFFF',
    iconType: 'settings',
    keywords: ['support', 'help', 'booking', 'troubleshoot', 'fix', 'appointment', 'schedule', 'gemini support', 'customer service'],
    description: 'Context-aware 24/7 AI Support Agent for multi-step service bookings & technical troubleshooting.',
    isSystem: true,
  },
  {
    id: 'rishi_comm',
    name: 'Messages & HD Calls',
    category: 'Social',
    packageName: 'ai.rishi.communications',
    scheme: '#',
    fallbackUrl: '#',
    iconBg: 'from-cyan-500 to-blue-600',
    iconColor: '#FFFFFF',
    iconType: 'messages',
    keywords: ['messages', 'chat', 'voice call', 'video call', 'webrtc', 'group chat', 'ai vision', 'calling', 'talk', 'rishi comm'],
    description: 'Ultra HD Voice, Video Calls, AI Vision screen analysis, and real-time messaging.',
    isSystem: true,
  },
  {
    id: 'youtube',
    name: 'YouTube',
    category: 'Media',
    packageName: 'com.google.android.youtube',
    scheme: 'intent://www.youtube.com/#Intent;package=com.google.android.youtube;scheme=https;end',
    fallbackUrl: 'https://www.youtube.com',
    iconBg: 'from-red-600 to-rose-700',
    iconColor: '#FFFFFF',
    iconType: 'youtube',
    keywords: ['youtube', 'yt', 'video', 'stream', 'vids', 'watch', 'media', 'shorts', 'song', 'music video'],
    description: 'Watch, stream, and discover trending videos worldwide.',
    isSystem: false,
    actionConfig: {
      searchUrlTemplate: 'https://www.youtube.com/results?search_query={q}',
      searchIntentTemplate: 'intent://www.youtube.com/results?search_query={q}#Intent;package=com.google.android.youtube;scheme=https;end',
      defaultQueryPlaceholder: 'Search songs, videos, tutorials...',
      quickSuggestions: ['Chill Lofi Music', 'Trending Songs', 'Coding Tutorials', 'Latest Tech News', 'Relaxing Jazz', 'Workout Mix'],
      supportedActions: ['search', 'play', 'view'],
    },
  },
  {
    id: 'whatsapp',
    name: 'WhatsApp',
    category: 'Social',
    packageName: 'com.whatsapp',
    scheme: 'intent://send#Intent;package=com.whatsapp;scheme=whatsapp;end',
    fallbackUrl: 'https://web.whatsapp.com',
    iconBg: 'from-emerald-500 to-green-600',
    iconColor: '#FFFFFF',
    iconType: 'whatsapp',
    keywords: ['whatsapp', 'wa', 'chat', 'message', 'call', 'social', 'messaging', 'text'],
    description: 'Simple, secure, and reliable messaging and calling.',
    isSystem: false,
    actionConfig: {
      searchUrlTemplate: 'https://web.whatsapp.com/send?text={q}',
      searchIntentTemplate: 'intent://send?text={q}#Intent;package=com.whatsapp;scheme=whatsapp;end',
      defaultQueryPlaceholder: 'Type a message or contact name...',
      quickSuggestions: ['Hello, are you available?', 'Check out this link!', 'Meeting at 5 PM', 'Sending notes'],
      supportedActions: ['message', 'search'],
    },
  },
  {
    id: 'chrome',
    name: 'Google Chrome',
    category: 'Utilities',
    packageName: 'com.android.chrome',
    scheme: 'intent://google.com/#Intent;package=com.android.chrome;scheme=https;end',
    fallbackUrl: 'https://www.google.com/chrome',
    iconBg: 'from-blue-500 via-amber-500 to-emerald-500',
    iconColor: '#FFFFFF',
    iconType: 'chrome',
    keywords: ['chrome', 'browser', 'google', 'web', 'internet', 'search', 'surf'],
    description: 'Fast, secure, and intuitive web browser by Google.',
    isSystem: true,
    actionConfig: {
      searchUrlTemplate: 'https://www.google.com/search?q={q}',
      searchIntentTemplate: 'intent://www.google.com/search?q={q}#Intent;package=com.android.chrome;scheme=https;end',
      defaultQueryPlaceholder: 'Search Google or type a URL...',
      quickSuggestions: ['Artificial Intelligence News', 'Best Laptops 2026', 'Weather forecast', 'Stock market today', 'Top movies this year'],
      supportedActions: ['search', 'view'],
    },
  },
  {
    id: 'spotify',
    name: 'Spotify',
    category: 'Media',
    packageName: 'com.spotify.music',
    scheme: 'intent://spotify.com/#Intent;package=com.spotify.music;scheme=https;end',
    fallbackUrl: 'https://open.spotify.com',
    iconBg: 'from-green-500 to-emerald-700',
    iconColor: '#FFFFFF',
    iconType: 'spotify',
    keywords: ['spotify', 'music', 'songs', 'audio', 'podcast', 'playlist', 'tune', 'track', 'album'],
    description: 'Stream millions of songs, playlists, and podcasts.',
    isSystem: false,
    actionConfig: {
      searchUrlTemplate: 'https://open.spotify.com/search/{q}',
      searchIntentTemplate: 'intent://open.spotify.com/search/{q}#Intent;package=com.spotify.music;scheme=https;end',
      defaultQueryPlaceholder: 'Search songs, artists, podcasts...',
      quickSuggestions: ['Today\'s Top Hits', 'Chill Acoustic', 'Deep Focus Beats', 'Hip Hop Central', 'Rock Classics', 'Sleep Sounds'],
      supportedActions: ['search', 'play', 'view'],
    },
  },
  {
    id: 'maps',
    name: 'Google Maps',
    category: 'Utilities',
    packageName: 'com.google.android.apps.maps',
    scheme: 'intent://maps.google.com/#Intent;package=com.google.android.apps.maps;scheme=https;end',
    fallbackUrl: 'https://maps.google.com',
    iconBg: 'from-emerald-600 via-teal-600 to-blue-600',
    iconColor: '#FFFFFF',
    iconType: 'maps',
    keywords: ['maps', 'gps', 'navigation', 'location', 'directions', 'traffic', 'find', 'places', 'restaurant', 'cafe', 'petrol'],
    description: 'Real-time GPS navigation, traffic updates, and local info.',
    isSystem: true,
    actionConfig: {
      searchUrlTemplate: 'https://www.google.com/maps/search/{q}',
      searchIntentTemplate: 'intent://maps.google.com/maps?q={q}#Intent;package=com.google.android.apps.maps;scheme=https;end',
      defaultQueryPlaceholder: 'Search places, restaurants, gas stations...',
      quickSuggestions: ['Coffee Shops Near Me', 'Italian Restaurants', 'Gas Stations', 'Pharmacies Open Now', 'Airports', 'Supermarkets'],
      supportedActions: ['search', 'navigate', 'view'],
    },
  },
  {
    id: 'playstore',
    name: 'Google Play Store',
    category: 'System',
    packageName: 'com.android.vending',
    scheme: 'intent://play.google.com/#Intent;package=com.android.vending;scheme=https;end',
    fallbackUrl: 'https://play.google.com',
    iconBg: 'from-cyan-500 via-blue-600 to-emerald-500',
    iconColor: '#FFFFFF',
    iconType: 'store',
    keywords: ['playstore', 'store', 'apps', 'games', 'download', 'market', 'install'],
    description: 'Explore, install, and update Android apps and games.',
    isSystem: true,
    actionConfig: {
      searchUrlTemplate: 'https://play.google.com/store/search?q={q}&c=apps',
      searchIntentTemplate: 'market://search?q={q}',
      defaultQueryPlaceholder: 'Search apps and games...',
      quickSuggestions: ['Top Action Games', 'Productivity Tools', 'Photo Editors', 'Music Streaming Apps', 'Fitness Trackers'],
      supportedActions: ['search', 'view'],
    },
  },
  {
    id: 'instagram',
    name: 'Instagram',
    category: 'Social',
    packageName: 'com.instagram.android',
    scheme: 'intent://instagram.com/#Intent;package=com.instagram.android;scheme=https;end',
    fallbackUrl: 'https://www.instagram.com',
    iconBg: 'from-amber-500 via-rose-500 to-purple-600',
    iconColor: '#FFFFFF',
    iconType: 'instagram',
    keywords: ['instagram', 'insta', 'ig', 'reels', 'photos', 'social', 'stories', 'creators'],
    description: 'Share photos, videos, and reels with friends.',
    isSystem: false,
    actionConfig: {
      searchUrlTemplate: 'https://www.instagram.com/explore/tags/{q}',
      searchIntentTemplate: 'intent://instagram.com/explore/tags/{q}#Intent;package=com.instagram.android;scheme=https;end',
      defaultQueryPlaceholder: 'Search tags, creators, trends...',
      quickSuggestions: ['photography', 'nature', 'travel', 'foodie', 'architecture', 'fitness'],
      supportedActions: ['search', 'view'],
    },
  },
  {
    id: 'twitter',
    name: 'X (Twitter)',
    category: 'Social',
    packageName: 'com.twitter.android',
    scheme: 'intent://twitter.com/#Intent;package=com.twitter.android;scheme=https;end',
    fallbackUrl: 'https://x.com',
    iconBg: 'from-zinc-900 to-black',
    iconColor: '#FFFFFF',
    iconType: 'twitter',
    keywords: ['twitter', 'x', 'tweets', 'news', 'social', 'trending', 'posts'],
    description: 'Real-time news, trending topics, and global conversation.',
    isSystem: false,
    actionConfig: {
      searchUrlTemplate: 'https://x.com/search?q={q}',
      searchIntentTemplate: 'intent://twitter.com/search?q={q}#Intent;package=com.twitter.android;scheme=https;end',
      defaultQueryPlaceholder: 'Search topics, hashtags, accounts...',
      quickSuggestions: ['AI News', 'Tech Breakthroughs', 'Space Exploration', 'Breaking News', 'Web Development'],
      supportedActions: ['search', 'view'],
    },
  },
  {
    id: 'netflix',
    name: 'Netflix',
    category: 'Media',
    packageName: 'com.netflix.mediaclient',
    scheme: 'intent://netflix.com/#Intent;package=com.netflix.mediaclient;scheme=https;end',
    fallbackUrl: 'https://www.netflix.com',
    iconBg: 'from-red-700 to-zinc-950',
    iconColor: '#E50914',
    iconType: 'netflix',
    keywords: ['netflix', 'movies', 'shows', 'series', 'cinema', 'stream', 'tv', 'watch'],
    description: 'Stream award-winning movies, TV shows, and documentaries.',
    isSystem: false,
    actionConfig: {
      searchUrlTemplate: 'https://www.netflix.com/search?q={q}',
      searchIntentTemplate: 'intent://www.netflix.com/search?q={q}#Intent;package=com.netflix.mediaclient;scheme=https;end',
      defaultQueryPlaceholder: 'Search movies, TV shows, genres...',
      quickSuggestions: ['Sci-Fi Thrillers', 'Award-Winning Dramas', 'Action & Adventure', 'Comedy Series', 'Documentaries'],
      supportedActions: ['search', 'play', 'view'],
    },
  },
  {
    id: 'gmail',
    name: 'Gmail',
    category: 'Productivity',
    packageName: 'com.google.android.gm',
    scheme: 'intent://mail.google.com/#Intent;package=com.google.android.gm;scheme=https;end',
    fallbackUrl: 'https://mail.google.com',
    iconBg: 'from-red-500 via-rose-500 to-red-700',
    iconColor: '#FFFFFF',
    iconType: 'gmail',
    keywords: ['gmail', 'email', 'mail', 'inbox', 'google mail', 'messages'],
    description: 'Fast, secure, and organized email for everyday communication.',
    isSystem: true,
    actionConfig: {
      searchUrlTemplate: 'https://mail.google.com/mail/u/0/#search/{q}',
      searchIntentTemplate: 'intent://mail.google.com/mail/u/0/#search/{q}#Intent;package=com.google.android.gm;scheme=https;end',
      defaultQueryPlaceholder: 'Search emails, receipts, senders...',
      quickSuggestions: ['receipts', 'flight reservations', 'unread messages', 'invoices', 'meeting invites'],
      supportedActions: ['search', 'compose', 'view'],
    },
  },
  {
    id: 'drive',
    name: 'Google Drive',
    category: 'Productivity',
    packageName: 'com.google.android.apps.docs',
    scheme: 'intent://drive.google.com/#Intent;package=com.google.android.apps.docs;scheme=https;end',
    fallbackUrl: 'https://drive.google.com',
    iconBg: 'from-amber-500 via-emerald-500 to-blue-600',
    iconColor: '#FFFFFF',
    iconType: 'drive',
    keywords: ['drive', 'cloud', 'files', 'docs', 'storage', 'backup', 'google drive'],
    description: 'Secure cloud storage and collaborative file synchronization.',
    isSystem: true,
    actionConfig: {
      searchUrlTemplate: 'https://drive.google.com/drive/search?q={q}',
      searchIntentTemplate: 'intent://drive.google.com/drive/search?q={q}#Intent;package=com.google.android.apps.docs;scheme=https;end',
      defaultQueryPlaceholder: 'Search documents, sheets, PDFs...',
      quickSuggestions: ['PDF Documents', 'Spreadsheets', 'Presentations', 'Recent Projects', 'Shared with me'],
      supportedActions: ['search', 'view'],
    },
  },
  {
    id: 'photos',
    name: 'Google Photos',
    category: 'Media',
    packageName: 'com.google.android.apps.photos',
    scheme: 'intent://photos.google.com/#Intent;package=com.google.android.apps.photos;scheme=https;end',
    fallbackUrl: 'https://photos.google.com',
    iconBg: 'from-amber-400 via-red-500 to-blue-600',
    iconColor: '#FFFFFF',
    iconType: 'photos',
    keywords: ['photos', 'gallery', 'pictures', 'backup', 'images', 'albums'],
    description: 'Organize, edit, and safely back up your photo gallery.',
    isSystem: true,
    actionConfig: {
      searchUrlTemplate: 'https://photos.google.com/search/{q}',
      searchIntentTemplate: 'intent://photos.google.com/search/{q}#Intent;package=com.google.android.apps.photos;scheme=https;end',
      defaultQueryPlaceholder: 'Search people, places, things in photos...',
      quickSuggestions: ['Vacation Photos', 'Mountains', 'Screenshots', 'Portraits', 'Cats and Dogs'],
      supportedActions: ['search', 'view'],
    },
  },
  {
    id: 'contacts',
    name: 'Contacts',
    category: 'System',
    packageName: 'com.google.android.contacts',
    scheme: 'intent:#Intent;action=android.intent.action.MAIN;category=android.intent.category.APP_CONTACTS;end',
    fallbackUrl: 'https://contacts.google.com',
    iconBg: 'from-blue-600 to-indigo-700',
    iconColor: '#FFFFFF',
    iconType: 'contacts',
    keywords: ['contacts', 'phonebook', 'address', 'people', 'numbers', 'call'],
    description: 'Manage and sync personal contact details and phone numbers.',
    isSystem: true,
    actionConfig: {
      searchUrlTemplate: 'https://contacts.google.com/search/{q}',
      searchIntentTemplate: 'intent:#Intent;action=android.intent.action.SEARCH;query={q};package=com.google.android.contacts;end',
      defaultQueryPlaceholder: 'Search name, number, email...',
      quickSuggestions: ['Family', 'Colleagues', 'Doctors', 'Recent Calls'],
      supportedActions: ['search', 'view'],
    },
  },
  {
    id: 'reddit',
    name: 'Reddit',
    category: 'Social',
    packageName: 'com.reddit.frontpage',
    scheme: 'intent://www.reddit.com/#Intent;package=com.reddit.frontpage;scheme=https;end',
    fallbackUrl: 'https://www.reddit.com',
    iconBg: 'from-orange-500 to-red-600',
    iconColor: '#FFFFFF',
    iconType: 'reddit',
    keywords: ['reddit', 'subreddits', 'threads', 'posts', 'discussions', 'community', 'news'],
    description: 'Dive into millions of communities and discussions.',
    isSystem: false,
    actionConfig: {
      searchUrlTemplate: 'https://www.reddit.com/search/?q={q}',
      searchIntentTemplate: 'intent://www.reddit.com/search/?q={q}#Intent;package=com.reddit.frontpage;scheme=https;end',
      defaultQueryPlaceholder: 'Search subreddits, posts, topics...',
      quickSuggestions: ['r/technology', 'r/webdev', 'r/artificial', 'r/science', 'r/AskReddit'],
      supportedActions: ['search', 'view'],
    },
  },
  {
    id: 'amazon',
    name: 'Amazon Shopping',
    category: 'Utilities',
    packageName: 'com.amazon.mShop.android.shopping',
    scheme: 'intent://amazon.com/#Intent;package=com.amazon.mShop.android.shopping;scheme=https;end',
    fallbackUrl: 'https://www.amazon.com',
    iconBg: 'from-amber-600 to-zinc-900',
    iconColor: '#FFFFFF',
    iconType: 'amazon',
    keywords: ['amazon', 'shopping', 'buy', 'store', 'order', 'deals', 'cart', 'products'],
    description: 'Shop millions of products with fast delivery.',
    isSystem: false,
    actionConfig: {
      searchUrlTemplate: 'https://www.amazon.com/s?k={q}',
      searchIntentTemplate: 'intent://www.amazon.com/s?k={q}#Intent;package=com.amazon.mShop.android.shopping;scheme=https;end',
      defaultQueryPlaceholder: 'Search products, electronics, deals...',
      quickSuggestions: ['Wireless Earbuds', 'Mechanical Keyboard', 'Smart Watches', 'Kindle Paperwhite', 'USB-C Hubs'],
      supportedActions: ['search', 'view'],
    },
  },
  {
    id: 'github',
    name: 'GitHub',
    category: 'Productivity',
    packageName: 'com.github.android',
    scheme: 'intent://github.com/#Intent;package=com.github.android;scheme=https;end',
    fallbackUrl: 'https://github.com',
    iconBg: 'from-zinc-800 to-black',
    iconColor: '#FFFFFF',
    iconType: 'github',
    keywords: ['github', 'git', 'repositories', 'code', 'open source', 'projects', 'developer'],
    description: 'Explore repositories, track code issues, and collaborate.',
    isSystem: false,
    actionConfig: {
      searchUrlTemplate: 'https://github.com/search?q={q}',
      searchIntentTemplate: 'intent://github.com/search?q={q}#Intent;package=com.github.android;scheme=https;end',
      defaultQueryPlaceholder: 'Search repositories, code, developers...',
      quickSuggestions: ['react', 'nextjs', 'gemini-api', 'typescript', 'tailwind-css', 'rust'],
      supportedActions: ['search', 'view'],
    },
  },
  {
    id: 'telegram',
    name: 'Telegram',
    category: 'Social',
    packageName: 'org.telegram.messenger',
    scheme: 'intent://telegram.org/#Intent;package=org.telegram.messenger;scheme=https;end',
    fallbackUrl: 'https://web.telegram.org',
    iconBg: 'from-sky-500 to-blue-600',
    iconColor: '#FFFFFF',
    iconType: 'telegram',
    keywords: ['telegram', 'tg', 'chat', 'messenger', 'channels', 'group'],
    description: 'Pure instant messaging — simple, fast, secure, and synced.',
    isSystem: false,
    actionConfig: {
      searchUrlTemplate: 'https://web.telegram.org/k/#?q={q}',
      searchIntentTemplate: 'tg://search?q={q}',
      defaultQueryPlaceholder: 'Search chats, channels, bots...',
      quickSuggestions: ['Tech News', 'Programming Hub', 'Crypto Updates', 'Book Club'],
      supportedActions: ['search', 'message'],
    },
  },
  {
    id: 'calculator',
    name: 'Calculator',
    category: 'Tools',
    packageName: 'com.google.android.calculator',
    scheme: 'intent:#Intent;action=android.intent.action.MAIN;category=android.intent.category.APP_CALCULATOR;end',
    fallbackUrl: 'https://www.google.com/search?q=calculator',
    iconBg: 'from-cyan-600 to-blue-700',
    iconColor: '#FFFFFF',
    iconType: 'calculator',
    keywords: ['calculator', 'calc', 'math', 'numbers', 'arithmetic', 'count', 'finance'],
    description: 'Perform simple and scientific math calculations.',
    isSystem: true,
    actionConfig: {
      searchUrlTemplate: 'https://www.google.com/search?q=calculator+{q}',
      searchIntentTemplate: 'intent:#Intent;action=android.intent.action.MAIN;category=android.intent.category.APP_CALCULATOR;end',
      defaultQueryPlaceholder: 'Calculate an expression (e.g. 45 * 12)...',
      quickSuggestions: ['25 * 40', '15% of 800', 'sqrt(144)', 'cos(45 deg)', '100 USD to EUR'],
      supportedActions: ['calculate', 'view'],
    },
  },
  {
    id: 'camera',
    name: 'Camera',
    category: 'System',
    packageName: 'com.android.camera',
    scheme: 'intent:#Intent;action=android.media.action.IMAGE_CAPTURE;end',
    fallbackUrl: 'https://photos.google.com',
    iconBg: 'from-violet-600 to-purple-800',
    iconColor: '#FFFFFF',
    iconType: 'camera',
    keywords: ['camera', 'cam', 'photo', 'picture', 'video', 'record', 'snap', 'selfie'],
    description: 'Capture high-definition photos and video recordings.',
    isSystem: true,
    actionConfig: {
      searchUrlTemplate: 'https://photos.google.com',
      searchIntentTemplate: 'intent:#Intent;action=android.media.action.IMAGE_CAPTURE;end',
      defaultQueryPlaceholder: 'Camera mode (Photo, Video, Selfie)...',
      quickSuggestions: ['Take Photo', 'Record Video', 'Selfie Mode', 'Scan QR Code'],
      supportedActions: ['camera_mode', 'view'],
    },
  },
  {
    id: 'settings',
    name: 'Settings',
    category: 'System',
    packageName: 'com.android.settings',
    scheme: 'intent:#Intent;action=android.settings.SETTINGS;end',
    fallbackUrl: 'https://support.google.com/android',
    iconBg: 'from-slate-600 to-zinc-800',
    iconColor: '#E2E8F0',
    iconType: 'settings',
    keywords: ['settings', 'config', 'preferences', 'setup', 'system', 'gear', 'options', 'android', 'wifi', 'bluetooth', 'display', 'battery'],
    description: 'Manage device settings, Wi-Fi, display, apps, and security.',
    isSystem: true,
    actionConfig: {
      searchUrlTemplate: 'https://support.google.com/android/search?q={q}',
      searchIntentTemplate: 'intent:#Intent;action=android.settings.SETTINGS;end',
      defaultQueryPlaceholder: 'Search setting (Wi-Fi, Bluetooth, Display)...',
      quickSuggestions: ['Wi-Fi Settings', 'Bluetooth Settings', 'Display & Brightness', 'Battery & Power', 'Apps Management'],
      supportedActions: ['setting', 'search', 'view'],
    },
  },
  {
    id: 'fps_boost',
    name: 'Experimental FPS Boost',
    category: 'System',
    packageName: 'com.rishi.fpsboost',
    scheme: 'intent:#Intent;action=android.settings.DISPLAY_SETTINGS;end',
    fallbackUrl: 'https://ais-dev-dolt3o3caljbmqcbny7utg-606708421040.asia-southeast1.run.app',
    iconBg: 'from-emerald-600 via-teal-600 to-cyan-700',
    iconColor: '#FFFFFF',
    iconType: 'settings',
    keywords: ['fps', 'boost', 'performance', 'frame rate', '60fps', '90fps', '120fps', 'graphics', 'game', 'speed', 'render', 'hz'],
    description: 'Experimental FPS controller and rendering performance optimizer (60/90/120 FPS).',
    isSystem: true,
  },
  {
    id: 'calendar',
    name: 'Google Calendar',
    category: 'Productivity',
    packageName: 'com.google.android.calendar',
    scheme: 'intent://calendar.google.com/#Intent;package=com.google.android.calendar;scheme=https;end',
    fallbackUrl: 'https://calendar.google.com',
    iconBg: 'from-blue-500 to-cyan-600',
    iconColor: '#FFFFFF',
    iconType: 'calendar',
    keywords: ['calendar', 'events', 'schedule', 'agenda', 'planner', 'reminders'],
    description: 'Schedule meetings, set reminders, and manage daily events.',
    isSystem: true,
  },
  {
    id: 'clock',
    name: 'Clock & Alarm',
    category: 'System',
    packageName: 'com.google.android.deskclock',
    scheme: 'intent:#Intent;action=android.intent.action.SHOW_ALARMS;end',
    fallbackUrl: 'https://www.google.com/search?q=timer',
    iconBg: 'from-indigo-600 to-slate-800',
    iconColor: '#FFFFFF',
    iconType: 'clock',
    keywords: ['clock', 'alarm', 'timer', 'stopwatch', 'time', 'wake'],
    description: 'Set alarms, manage world clocks, and run precision timers.',
    isSystem: true,
  },
  {
    id: 'phone',
    name: 'Phone',
    category: 'System',
    packageName: 'com.google.android.dialer',
    scheme: 'tel:',
    fallbackUrl: 'https://contacts.google.com',
    iconBg: 'from-emerald-500 to-teal-700',
    iconColor: '#FFFFFF',
    iconType: 'phone',
    keywords: ['phone', 'dialer', 'call', 'telephone', 'mobile', 'voicemail'],
    description: 'Make voice calls, check missed calls, and manage dialer.',
    isSystem: true,
  },
  {
    id: 'messages',
    name: 'Messages',
    category: 'System',
    packageName: 'com.google.android.apps.messaging',
    scheme: 'intent:#Intent;action=android.intent.action.MAIN;category=android.intent.category.APP_MESSAGING;end',
    fallbackUrl: 'https://messages.google.com',
    iconBg: 'from-blue-600 to-sky-600',
    iconColor: '#FFFFFF',
    iconType: 'messages',
    keywords: ['messages', 'sms', 'text', 'mms', 'inbox', 'chat'],
    description: 'Send and receive SMS, MMS, and RCS chat messages.',
    isSystem: true,
  },
  {
    id: 'files',
    name: 'Files',
    category: 'System',
    packageName: 'com.google.android.apps.nbu.files',
    scheme: 'intent:#Intent;action=android.intent.action.GET_CONTENT;type=*/*;end',
    fallbackUrl: 'https://drive.google.com',
    iconBg: 'from-blue-600 via-cyan-500 to-teal-600',
    iconColor: '#FFFFFF',
    iconType: 'file',
    keywords: ['files', 'storage', 'downloads', 'explorer', 'documents', 'folders'],
    description: 'Browse, organize, and clean up local files and downloads.',
    isSystem: true,
  },
  {
    id: 'wallpaper_studio',
    name: 'Wallpaper & Video Studio',
    category: 'Tools',
    packageName: 'com.ai.wallpaper.studio',
    scheme: 'intent:#Intent;action=android.intent.action.SET_WALLPAPER;end',
    fallbackUrl: '',
    iconBg: 'from-orange-500 via-amber-500 to-purple-600',
    iconColor: '#FFFFFF',
    iconType: 'generic',
    keywords: ['wallpaper', 'video wallpaper', 'live wallpaper', 'background', 'video', 'samurai', 'theme', 'custom video'],
    description: 'Set 4K live video wallpapers, upload custom videos, and customize shaders.',
    isSystem: true,
  }
];
