import { VerifiedSourceItem, SourceTier } from './types';

/**
 * SourceVerifier: Evaluates trustworthiness, checks domain authority based on a strict 7-tier priority hierarchy,
 * filters low-quality SEO spam / scraped links, and ranks verified sources.
 */
export class SourceVerifier {
  // Tier 1: Official Government
  private static OFFICIAL_GOVERNMENT = [
    '.gov', '.gov.in', '.nic.in', '.gov.uk', '.europa.eu', '.mil', '.who.int', '.un.org',
    'pmindia.gov.in', 'presidentofindia.gov.in', 'whitehouse.gov', 'isro.gov.in', 'nasa.gov', 'pib.gov.in', 'rbi.org.in'
  ];

  // Tier 2: Official Company / Product
  private static OFFICIAL_COMPANY = [
    'apple.com', 'google.com', 'microsoft.com', 'openai.com', 'samsung.com', 'tesla.com',
    'amazon.com', 'meta.com', 'nvidia.com', 'github.com', 'oracle.com', 'ibm.com', 'intel.com',
    'anthropic.com', 'cloudflare.com'
  ];

  // Tier 3: Official Documentation & Package Registries
  private static OFFICIAL_DOCS = [
    'docs.python.org', 'developer.mozilla.org', 'pypi.org', 'npmjs.com', 'react.dev',
    'typescriptlang.org', 'go.dev', 'rust-lang.org', 'flutter.dev', 'developer.android.com',
    'developer.apple.com', 'docs.github.com', 'cloud.google.com/docs', 'aws.amazon.com/docs'
  ];

  // Tier 4: Universities & Research Institutions
  private static ACADEMIC = [
    '.edu', '.ac.in', '.ac.uk', 'arxiv.org', 'nature.com', 'science.org', 'ieee.org',
    'springer.com', 'mit.edu', 'stanford.edu', 'harvard.edu', 'ox.ac.uk', 'cam.ac.uk'
  ];

  // Tier 5: Reputable News Organizations
  private static REPUTABLE_NEWS = [
    'reuters.com', 'apnews.com', 'bloomberg.com', 'bbc.com', 'bbc.co.uk', 'nytimes.com',
    'wsj.com', 'ft.com', 'thehindu.com', 'indianexpress.com', 'ndtv.com', 'hindustantimes.com',
    'economist.com', 'aljazeera.com', 'theguardian.com', 'cnbc.com', 'forbes.com', 'time.com'
  ];

  // Tier 6: Technical Publications
  private static TECH_PUBLICATIONS = [
    'techcrunch.com', 'theverge.com', 'arstechnica.com', 'wired.com', 'zdnet.com',
    'cnet.com', 'anandtech.com', 'tomshardware.com', 'engadget.com', 'venturebeat.com'
  ];

  // Low-Quality / SEO Spam / Scraper domains to penalize
  private static LOW_QUALITY_PATTERNS = [
    'ezinearticles', 'contentfarm', 'scrapednews', 'clickbait', 'prizes-win', 'autogenerated'
  ];

  /**
   * Verifies, scores, and ranks a list of sources according to the 7-tier hierarchy.
   */
  public static verifyAndRank(sources: VerifiedSourceItem[]): VerifiedSourceItem[] {
    const verified = sources.map(source => {
      const domain = source.domain.toLowerCase();
      let score = 70;
      let isOfficial = false;
      let tier: SourceTier = 'general';

      // Tier 1: Official Government
      if (this.OFFICIAL_GOVERNMENT.some(d => domain.endsWith(d) || domain.includes(d))) {
        score = 99;
        isOfficial = true;
        tier = 'official_government';
      }
      // Tier 2: Official Company / Product
      else if (this.OFFICIAL_COMPANY.some(c => domain.includes(c))) {
        score = 96;
        isOfficial = true;
        tier = 'official_company';
      }
      // Tier 3: Official Documentation
      else if (this.OFFICIAL_DOCS.some(doc => domain.includes(doc)) || domain.startsWith('docs.') || domain.startsWith('developer.')) {
        score = 95;
        isOfficial = true;
        tier = 'official_docs';
      }
      // Tier 4: Academic & Research
      else if (this.ACADEMIC.some(a => domain.endsWith(a) || domain.includes(a))) {
        score = 93;
        tier = 'academic';
      }
      // Tier 5: Reputable News
      else if (this.REPUTABLE_NEWS.some(news => domain.includes(news))) {
        score = 90;
        tier = 'reputable_news';
      }
      // Tier 6: Technical Publications
      else if (this.TECH_PUBLICATIONS.some(tech => domain.includes(tech))) {
        score = 85;
        tier = 'tech_publication';
      }
      // Check Low Quality / Spam
      else if (this.LOW_QUALITY_PATTERNS.some(spam => domain.includes(spam))) {
        score = 20;
        tier = 'low_quality';
      }

      return {
        ...source,
        authoritativeScore: score,
        isOfficial,
        sourceTier: tier,
      };
    });

    // Filter out severe low-quality entries if higher authority sources are available
    const filtered = verified.filter(s => s.sourceTier !== 'low_quality' || verified.length <= 2);

    // Sort descending by authority score
    return filtered.sort((a, b) => b.authoritativeScore - a.authoritativeScore);
  }

  /**
   * Identifies whether any high-authority official or top-tier news sources exist.
   */
  public static hasAuthoritativeSources(sources: VerifiedSourceItem[]): boolean {
    return sources.some(s => s.isOfficial || s.sourceTier === 'official_government' || s.sourceTier === 'official_company' || s.sourceTier === 'official_docs' || s.sourceTier === 'reputable_news');
  }
}
