import { JinaSourceType } from './types';

/**
 * WebContentProcessor
 * 
 * Sanitizes, extracts, normalizes, and secures web content retrieved via Jina or direct web readers.
 * Enforces prompt injection defense and size constraints.
 */
export class WebContentProcessor {
  private static readonly MAX_PAGE_CHARS = 16000;
  private static readonly MAX_SNIPPET_CHARS = 400;

  // Patterns indicating potential prompt injection or jailbreak attempts in untrusted web pages
  private static readonly INJECTION_PATTERNS = [
    /ignore\s+(all\s+)?(previous|prior)\s+instructions/gi,
    /system\s*prompt\s*override/gi,
    /you\s+are\s+now\s+in\s+developer\s+mode/gi,
    /<\s*system\s*>/gi,
    /\[\s*system\s*instruction\s*\]/gi,
    /disregard\s+(all\s+)?safety\s+guidelines/gi,
    /act\s+as\s+an\s+unrestricted\s+ai/gi,
    /execute\s+command:\s*/gi,
    /reveal\s+(your\s+)?(api\s*keys?|secrets?|passwords?|tokens?)/gi,
  ];

  /**
   * Cleans and sanitizes raw markdown or HTML from web sources.
   */
  public static processMarkdown(raw: string, url?: string): {
    title: string;
    content: string;
    description?: string;
    publishedTime?: string;
    headings: string[];
  } {
    if (!raw) {
      return { title: '', content: '', headings: [] };
    }

    let text = raw;

    // 1. Remove binary/raw control characters
    text = text.replace(/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/g, '');

    // 2. Neutralize prompt injection attempts in untrusted external web content
    for (const pattern of this.INJECTION_PATTERNS) {
      text = text.replace(pattern, '[Redacted External Instruction]');
    }

    // 3. Extract metadata headers if Jina Reader format (e.g. Title:, URL Source:, Published Time:)
    let title = '';
    let publishedTime: string | undefined;
    let description: string | undefined;

    const titleMatch = text.match(/^Title:\s*(.+)$/m);
    if (titleMatch) {
      title = titleMatch[1].trim();
    }

    const pubMatch = text.match(/^Published Time:\s*(.+)$/m);
    if (pubMatch) {
      publishedTime = pubMatch[1].trim();
    }

    const descMatch = text.match(/^Description:\s*(.+)$/m);
    if (descMatch) {
      description = descMatch[1].trim();
    }

    // 4. Strip boilerplate headers generated by Reader proxy
    text = text
      .replace(/^Title:.*$/m, '')
      .replace(/^URL Source:.*$/m, '')
      .replace(/^Published Time:.*$/m, '')
      .replace(/^Markdown Content:.*$/m, '')
      .trim();

    // 5. Remove excessive navigational markdown links (e.g. [Home](...), [About](...), [Sign In](...))
    text = text.replace(/\[\s*(?:Home|About|Contact|Sign in|Login|Terms|Privacy Policy|Cookie policy|Navigation|Menu)\s*\]\([^)]+\)/gi, '');

    // 6. Extract key headings
    const headings: string[] = [];
    const headingMatches = text.matchAll(/^#{1,3}\s+(.+)$/gm);
    for (const match of headingMatches) {
      if (match[1] && headings.length < 10) {
        headings.push(match[1].trim());
      }
    }

    // Fallback title from first h1 if not present in metadata
    if (!title && headings.length > 0) {
      title = headings[0];
    } else if (!title && url) {
      title = this.extractDomain(url);
    }

    // 7. Normalize redundant spacing and blank lines
    text = text
      .replace(/\n{3,}/g, '\n\n')
      .replace(/[ \t]{2,}/g, ' ')
      .trim();

    // 8. Truncate gracefully if oversized
    if (text.length > this.MAX_PAGE_CHARS) {
      const cutoff = text.lastIndexOf('\n\n', this.MAX_PAGE_CHARS);
      text = text.slice(0, cutoff > 5000 ? cutoff : this.MAX_PAGE_CHARS) + '\n\n... [Content summarized to fit context budget]';
    }

    return {
      title: title || 'Web Source Document',
      content: text,
      description,
      publishedTime,
      headings,
    };
  }

  /**
   * Generates a concise clean snippet from page content or summary.
   */
  public static createSnippet(content: string, maxLen: number = WebContentProcessor.MAX_SNIPPET_CHARS): string {
    if (!content) return '';
    const clean = content
      .replace(/#+\s+/g, '')
      .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1')
      .replace(/\s+/g, ' ')
      .trim();

    if (clean.length <= maxLen) return clean;
    return `${clean.slice(0, maxLen - 3)}...`;
  }

  /**
   * Extracts clean domain name from URL.
   */
  public static extractDomain(url: string): string {
    try {
      const parsed = new URL(url);
      return parsed.hostname.replace(/^www\./, '');
    } catch {
      return url.split('/')[2]?.replace(/^www\./, '') || url;
    }
  }

  /**
   * Classifies source type into an authoritative tier.
   */
  public static classifySourceType(url: string, title: string): JinaSourceType {
    const lowerUrl = url.toLowerCase();
    const domain = this.extractDomain(url).toLowerCase();

    if (
      domain.endsWith('.gov') ||
      domain.includes('.gov.') ||
      domain.includes('.nic.in') ||
      domain.includes('who.int') ||
      domain.includes('un.org') ||
      domain.includes('europa.eu')
    ) {
      return 'government';
    }

    if (
      domain.endsWith('.edu') ||
      domain.includes('.ac.') ||
      domain.includes('arxiv.org') ||
      domain.includes('nature.com') ||
      domain.includes('sciencedirect.com') ||
      domain.includes('ieee.org') ||
      domain.includes('nih.gov') ||
      domain.includes('pubmed')
    ) {
      return 'academic';
    }

    if (
      domain.includes('docs.') ||
      domain.includes('developer.') ||
      domain.includes('github.com') ||
      domain.includes('gitlab.com') ||
      domain.includes('pkg.go.dev') ||
      domain.includes('npmjs.com') ||
      domain.includes('pypi.org') ||
      domain.includes('rust-lang.org') ||
      domain.includes('mozilla.org') ||
      domain.includes('w3.org') ||
      domain.includes('microsoft.com/learn') ||
      lowerUrl.includes('/docs/') ||
      lowerUrl.includes('/documentation/') ||
      lowerUrl.includes('/api-reference/')
    ) {
      return 'official_doc';
    }

    if (
      domain.includes('apple.com') ||
      domain.includes('google.com') ||
      domain.includes('microsoft.com') ||
      domain.includes('amazon.com') ||
      domain.includes('meta.com') ||
      domain.includes('openai.com') ||
      domain.includes('anthropic.com') ||
      domain.includes('nvidia.com') ||
      domain.includes('jina.ai') ||
      domain.includes('vercel.com')
    ) {
      return 'company';
    }

    if (
      domain.includes('reuters.com') ||
      domain.includes('apnews.com') ||
      domain.includes('bbc.com') ||
      domain.includes('bloomberg.com') ||
      domain.includes('wsj.com') ||
      domain.includes('nytimes.com') ||
      domain.includes('theguardian.com') ||
      domain.includes('ft.com') ||
      domain.includes('cnbc.com') ||
      domain.includes('techcrunch.com') ||
      domain.includes('theverge.com') ||
      domain.includes('arstechnica.com')
    ) {
      return 'reputable_news';
    }

    if (
      domain.includes('stackoverflow.com') ||
      domain.includes('medium.com') ||
      domain.includes('dev.to') ||
      domain.includes('hashnode.dev') ||
      domain.includes('hackernews') ||
      domain.includes('reddit.com')
    ) {
      return 'community';
    }

    return 'general_web';
  }

  /**
   * Computes a relevance & authoritative quality score (0-100).
   */
  public static calculateRelevanceScore(
    sourceType: JinaSourceType,
    title: string,
    content: string,
    query: string
  ): number {
    let base = 50;

    switch (sourceType) {
      case 'official_doc':
        base = 95;
        break;
      case 'government':
        base = 94;
        break;
      case 'academic':
        base = 90;
        break;
      case 'company':
        base = 88;
        break;
      case 'reputable_news':
        base = 82;
        break;
      case 'technical':
        base = 75;
        break;
      case 'community':
        base = 65;
        break;
      default:
        base = 55;
    }

    // Boost score if query terms are in title
    const queryTerms = query.toLowerCase().split(/\s+/).filter(t => t.length > 2);
    const lowerTitle = title.toLowerCase();
    const matchesInTitle = queryTerms.filter(term => lowerTitle.includes(term)).length;
    const titleBoost = Math.min(10, matchesInTitle * 3);

    return Math.min(100, base + titleBoost);
  }
}
