import React from 'react';
import {
  MagnifyingGlassIcon,
  PaperClipIcon,
  MicrophoneIcon,
  PaperAirplaneIcon,
  PlusIcon,
  DocumentDuplicateIcon,
  TrashIcon,
  PencilSquareIcon,
  Cog6ToothIcon,
  UserCircleIcon,
  FolderIcon,
  BookOpenIcon,
  GlobeAltIcon,
  XMarkIcon,
  CheckIcon,
  EllipsisHorizontalIcon,
  EllipsisVerticalIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  ArrowPathIcon,
  ShareIcon,
  SparklesIcon,
  Bars3Icon,
  ArrowDownTrayIcon,
  ArrowUpTrayIcon,
  QuestionMarkCircleIcon,
  LightBulbIcon,
  ChatBubbleOvalLeftEllipsisIcon,
  SpeakerWaveIcon,
  SpeakerXMarkIcon,
  PhoneIcon,
  PhotoIcon,
  VideoCameraIcon,
  CpuChipIcon,
  FunnelIcon,
  ClockIcon,
  BookmarkIcon,
  StarIcon,
  ArrowRightIcon,
  ExclamationCircleIcon,
  ArrowLeftIcon,
  AdjustmentsHorizontalIcon,
} from '@heroicons/react/24/outline';

import {
  SparklesIcon as SparklesSolidIcon,
  CheckCircleIcon as CheckCircleSolidIcon,
  StarIcon as StarSolidIcon,
  BookmarkIcon as BookmarkSolidIcon,
  MicrophoneIcon as MicrophoneSolidIcon,
} from '@heroicons/react/24/solid';

export {
  MagnifyingGlassIcon as SearchIcon,
  PaperClipIcon as AttachmentIcon,
  MicrophoneIcon as VoiceIcon,
  MicrophoneSolidIcon,
  PaperAirplaneIcon as SendIcon,
  PlusIcon,
  DocumentDuplicateIcon as CopyIcon,
  TrashIcon as DeleteIcon,
  PencilSquareIcon as EditIcon,
  Cog6ToothIcon as SettingsIcon,
  UserCircleIcon as UserIcon,
  FolderIcon as ProjectsIcon,
  BookOpenIcon as LibraryIcon,
  GlobeAltIcon as GlobeIcon,
  XMarkIcon as CloseIcon,
  CheckIcon,
  CheckCircleSolidIcon,
  EllipsisHorizontalIcon as MoreHorizontalIcon,
  EllipsisVerticalIcon as MoreVerticalIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  ArrowPathIcon as RefreshIcon,
  ShareIcon,
  SparklesIcon,
  SparklesSolidIcon,
  Bars3Icon as MenuIcon,
  ArrowDownTrayIcon as DownloadIcon,
  ArrowUpTrayIcon as UploadIcon,
  QuestionMarkCircleIcon as HelpIcon,
  LightBulbIcon as IdeaIcon,
  ChatBubbleOvalLeftEllipsisIcon as ChatIcon,
  SpeakerWaveIcon as VolumeIcon,
  SpeakerXMarkIcon as MuteIcon,
  PhoneIcon as CallIcon,
  PhotoIcon as ImageIcon,
  VideoCameraIcon as VideoIcon,
  CpuChipIcon as ModelIcon,
  FunnelIcon as FilterIcon,
  ClockIcon as HistoryIcon,
  BookmarkIcon,
  BookmarkSolidIcon,
  StarIcon,
  StarSolidIcon,
  ArrowRightIcon,
  ArrowLeftIcon,
  ExclamationCircleIcon as AlertIcon,
  AdjustmentsHorizontalIcon as SlidersIcon,
};
